version: '2'
services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    image: sweepai/sweep
    volumes:
      - .:/app
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    mem_limit: 48g
    command: >
      sh -c "echo PORT: ${PORT:-8080} && . bin/startup.sh"
    stdin_open: true
    tty: true
    environment:
      - PORT=${PORT:-8080}
    env_file:
      - .env
  sandbox:
    build:
      context: sweepai/sandbox
      dockerfile: Dockerfile.sandbox
    image: sweepai/sandbox
  sandbox-web:
    build:
      context: sweepai/sandbox
      dockerfile: Dockerfile.web
    image: sweepai/sandbox-web
    ports:
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
