version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/app
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    mem_limit: 48g
    command: >
      sh -c "echo PORT: ${PORT:-8080} && . bin/startup.sh"
    stdin_open: true
    tty: true
    environment:
      - PORT=${PORT:-8080}
