name: Sweep Issue (Don't use this unless you want to change our repository. Sweep runs in your own repository)
title: 'Sweep: '
description: For small bugs, features, refactors, and tests to be handled by Sweep, an AI-powered junior developer.
labels: sweep
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details for Sweep
      placeholder: |
        When prompting Sweep, tell it where and what to edit and provide enough context for a new developer to the codebase.
        
        Examples:
        Bugs: The bug might be in ... file. Here are the logs: ...
        Features: the new endpoint should use the ... class from ... file because it contains ... logic.
        Refactors: We are migrating this function to ... version because ...
