name: Run pytest on push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest on committed files
      run: |
        for file in $(git diff --name-only HEAD~1); do
          if [[ $file == sweepai/* ]]; then
            test_file="tests/${file#sweepai/}_test.py"
            if [[ -f $test_file ]]; then
              pytest $test_file
            fi
          fi
        done
